config/routes.rb
Rails.application.routes.draw do

	# devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

	devise_for  :users, 
				:path_prefix => 'welcome', 
				:controllers => { registrations: 'registrations', 
					:omniauth_callbacks => "callbacks" }

	devise_scope :user do
  		root to: "devise/registrations#new"
	end

	resources :users, only: [:show] do
		resources :lists do
			resources :movies
		end
	end
  

end

app/models/list.rb
class List < ApplicationRecord

	validates :name, presence: true, length: { minimum: 2, maximum: 20 }

	# ONE to MANY: User > List
	belongs_to :user, optional: true

	# JOIN: List < Movies
	has_many :movie_lists
	has_many :movies, :through => :movie_lists

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @user = User.find(params[:user_id])
    @lists = @user.lists.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @user = User.find(params[:user_id])
    @list = List.find(params[:id])
    render :show
  end

  # GET /lists/new
  def new
    @list = List.new
    @user = User.find(params[:user_id]).id
  end

  # GET /lists/1/edit
  def edit
    @user = User.find(params[:user_id])
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params_create)

    respond_to do |format|
      if @list.save
        format.html { redirect_to user_lists_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params_update)
        format.html { redirect_to user_lists_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to user_lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end
    # list param for create without require list
    def list_params_create
      params.permit(:name, :user_id, lists_attributes: [:id])
    end
    # list params for update with require list
    def list_params_update
      params.require(:list).permit(:name, :user_id, lists_attributes: [:id])
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with url: { action: "create" }  do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :name %><br />
  <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div id="list-container" class="container">
  <div class="row">


		<h3 class="list-h3">Editing List</h3>

		<%= form_for @list, url: user_list_path(@user,@list) do |form| %>
		  <div class="field">
		    <h5 class="list-h5"><%= form.label :name %></h5>
		    <br />
		    <%= form.text_field :name , class: "form-control" %>
		  </div>
		  <div class="actions">
		    <button class="btn"><%= form.submit %></button>
		  </div>
		<% end %>

		<button class="btn"><%= link_to 'Show', user_list_path %> </button>
		<button class="btn"><%= link_to 'Back', user_lists_path %> </button>

	</div>
</div>

app/views/lists/index.html.erb
<div id="list-container" class="container">
  <div class="row">

    <p id="notice"><%= notice %></p>

    <h3 class='list-h3'>My Lists</h3>

    <% @lists.each do |list| %>

      <div id="list-container" class="container">
        <div class="row">
      
            <h1 class="list-h1 col-md-8"><%= link_to list.name, user_list_movies_path(@user,list) %></h1>
            <button class="btn col-md-1 align-baseline"><%= link_to 'Edit', edit_user_list_path(@user,list) %></button>
            <button class="btn col-md-1 align-baseline"><%= link_to 'Delete', user_list_path(@user,list), method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </div>
      </div>

    <% end %>

    <br>

    <button class="btn"><%= link_to 'New List', new_user_list_path(@user) %></button>

  </div>
</div>

app/views/lists/new.html.erb
<h1 class="list-h1">New List</h1>

<%= render 'form', list: @list %>

<button class="btn"><%= link_to 'Back', user_lists_path %></button>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_list_path(@list) %> |
<%= link_to 'Back', user_lists_path %>

<%= @list.name %>